local_backend: true
backend:
  name: github
  repo: mafia-kumat/mafia-kumat-website
  branch: master

media_folder: 'public/media'
public_folder: '/media'

collections:
  - name: 'chapters'
    label: 'Materi Belajar'
    folder: 'src/app/materi/(chapters)'
    create: true
    path: '{{slug}}/page'
    extension: 'mdx'
    format: 'frontmatter'
    fields:
      - { label: 'Judul Bab', name: 'title', widget: 'string' }
      - { label: 'Nomor Urut', name: 'order', widget: 'number', value_type: 'int' }
      - { label: 'Deskripsi Singkat', name: 'description', widget: 'text' }
      - { label: 'Isi Materi', name: 'body', widget: 'markdown', hint: 'Ketik: <GDrivePDF id="ID_DRIVE" title="Judul" /> untuk menyisipkan PDF dari Google Drive.' }
